name: 🆕 Suggest an improvement or new feature
description: ———
labels: enhancement, under discussion
body:
  - type: markdown
    attributes:
      value: 👋 Consider contributing by fixing some [easy bugs](https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3Abug).
  - type: textarea
    attributes:
      label: Description
      description: 'Please ensure your requested feature makes sense for Refined GitHub: https://github.com/refined-github/refined-github/issues/2960'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot
      description: You can provide screenshots/mockups to better visualize your idea. Files can be dropped in this field
  - type: textarea
    attributes:
      label: Example URLs
      description: Include a REAL URL where the feature should appear. e.g. Do you want a feature to appear on the main page of a repo? Paste a link to a repo
      placeholder: https://github.com/refined-github/refined-github
    validations:
      required: true
